Repository d4a-jtk19-webdev/proyek-webdev-d4a-2021, pull requests merged in 2021-12, with the labels that each got.

#8 📝 back-end : README.md
  service-monitoring/docs/README.md
Labels: documentation

#13 BackEnd : Association Error Hotfix
  backend/src/associations.js
Labels: bug

#16 BackEnd: API Get Jabatan By NIP
  backend/src/associations.js
  backend/src/controller/Dosen.js
  backend/src/dao/Dosen.js
  backend/src/routes/Dosen.js
  postgres-database/src/models/Menjabat.js
Labels: enhancement

#18 BackEnd: API Progress Tugas By Date Range
  service-monitoring/src/controller/Mahasiswa.js
  service-monitoring/src/dao/Mahasiswa.js
  service-monitoring/src/routes/Mahasiswa.js
Labels: documentation

#22 BackEnd : Fix Bug
  backend/src/controller/Jadwal.js
Labels: bug

#23 BackEnd: Jabatan Association Error Hotfix
  backend/src/associations.js
Labels: bug
